package lib;


/**
* lib/_LibraryImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lib.idl
* Saturday, 4 March, 2017 1:04:28 PM IST
*/

public abstract class _LibraryImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements lib.Library, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _LibraryImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("issue", new java.lang.Integer (0));
    _methods.put ("Return", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // lib/Library/issue
       {
         int x = in.read_long ();
         int $result = (int)0;
         $result = this.issue (x);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // lib/Library/Return
       {
         int x = in.read_long ();
         int $result = (int)0;
         $result = this.Return (x);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:lib/Library:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _LibraryImplBase
