package lib;


/**
* lib/Library.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lib.idl
* Saturday, 4 March, 2017 1:04:28 PM IST
*/

public interface Library extends LibraryOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Library
