package lib;


/**
* lib/LibraryOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lib.idl
* Saturday, 4 March, 2017 1:04:28 PM IST
*/

public interface LibraryOperations 
{
  int issue (int x);
  int Return (int x);
} // interface LibraryOperations
