package lib;

/**
* lib/LibraryHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lib.idl
* Saturday, 4 March, 2017 1:04:28 PM IST
*/

public final class LibraryHolder implements org.omg.CORBA.portable.Streamable
{
  public lib.Library value = null;

  public LibraryHolder ()
  {
  }

  public LibraryHolder (lib.Library initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = lib.LibraryHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    lib.LibraryHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return lib.LibraryHelper.type ();
  }

}
